### ISSUE TITLE
[Milestone] MilestoneFormComponent UI 구현

### ISSUE THREAD

**Issue by zunopark** [boostcamp-2020/IssueTracker-31#116]
- [ ] create milestone 클릭 시 milestone 생성 요청
- [ ] 날짜 입력 태그는 "연도.월.일" 형식
- [ ] 날짜 입력 값 검증 후 유효하지 않으면 빨간색으로 표시
- [ ] cancel 클릭 시 milestoneListComponent로 전환
