### ISSUE TITLE
[BE] 전체 milestone detail API

### ISSUE THREAD

**Issue by bell-won** [boostcamp-2020/IssueTracker-31#87]
- [x] GET milestones/detail
- [x] title, progress, due date, description
- [x] open issue 개수
- [x] close issue 개수
